### ISSUE TITLE
Handle double-click on map

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#31] opened 2021-03-05 14:41 UTC
Currently double-cklicking the map makes the map unusable, so we should either define a specific handler action for double-clic, ie. zoom in, or make sure double-clicks are ignored.

**Comment by sanak** [comment] 2021-05-19 06:04
@dkastl  
Did this happen on issue creating/editing time ?  
I couldn't reproduce the issue on `develop` branch, so I am thinking to close this issue.

**Comment by dkastl** [comment] 2021-05-19 06:47
Maybe it's resolved already. It may have happened in the old version.

**Comment by sanak** [comment] 2021-05-19 07:24
Okay, thanks for confirmation.
Then, I will close this.

**Closed by sanak** 2021-05-19 07:24 UTC
Labels: bug
