### ISSUE TITLE
Remove Geocoder from map toolbar if not enabled

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#29] opened 2021-03-05 14:37 UTC
The Geocoder toolbar icon is still visible even if the Geocoder configuration is empty.

**Comment by sanak** [comment] 2021-05-19 05:50
This seems to be done already, but I will check it, again.

**Comment by sanak** [comment] 2021-07-14 00:41
@dkastl  
I confirmed that this is implemented in the following lines, but I felt that using ol-ext Search control is better UI/UX.
- https://viglino.github.io/ol-ext/examples/search/map.control.search.html

I will close this issue, then create new enhancement issue for ol-ext Search control.

**Closed by sanak** 2021-07-14 00:41 UTC
Labels: bug, geocoder

**Comment by dkastl** [comment] 2021-07-14 00:42
OK
